name: nightly-ritual

on:
  schedule:
    - cron: '0 11 * * *'   # JST 20:00
  workflow_dispatch: {}

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: article-agent/src   # ← サブフォルダのsrcを指定
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AGENT_BACKUP_TOPICS: ${{ secrets.AGENT_BACKUP_TOPICS }}
    steps:
      - uses: actions/checkout@v4

      - name: Show cwd and files (debug)
        run: |
          pwd
          ls -la

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        working-directory: article-agent       # ★ここ！
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Ensure dirs
        working-directory: article-agent       # ★ここ！
        run: |
          mkdir -p outputs logs

      - name: Run pipeline (dummy text but Slack ON)
        working-directory: article-agent       # ★ここ！
        run: |
          python - << 'PY'
          import json
          from article_agent.pipeline import run_once
          rec = run_once(use_dummy_model=True, try_webhook_first=True)
          print(json.dumps(rec, ensure_ascii=False, indent=2))
          PY

      - name: Upload outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: article-md
          path: article-agent/outputs/*.md
          if-no-files-found: ignore

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: article-agent/logs/*
          if-no-files-found: ignore
